import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
 
import Layout from "@/src/components/Layout";
import { getLocale, getMessages } from "next-intl/server";
import { notFound } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: any;
};
export default  async function RootLayout({ children, params: { locale } }: Props) {
     let messages;
     try {
       messages = (await import(`../../messages/${locale}.json`)).default;
     } catch (error) {
       notFound();
     }
 
    
  return (
    <html lang={locale} dir={locale == "en" ? "ltr" : "rtl"}>
      <body className={inter.className}>
        <Layout locale={locale} messages={messages}>
          {children}
        </Layout>
      </body>
    </html>
  );
}
